# config/database.yml

development: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  # Crucial: Reads the hostname/credentials from the docker-compose environment
  host: <%= ENV.fetch("DATABASE_HOST") %>
  username: <%= ENV.fetch("DATABASE_USERNAME") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") %>
  database: <%= ENV.fetch("DATABASE_NAME") %>
  structure_dump_flags: "--skip-ssl"
